log style tweak, add log level option,  show process name and path in connections page
Dreamacro/clash-dashboard pull request #93
Opened 2022-04-14 22:16 UTC by MetaCubeX

Chore: log style tweak
Feat: add log level option, show process name and path in connections page

2022-04-14 22:23 UTC, MetaCubeX commented
![Screenshot 2022-04-15 062119](https://user-images.githubusercontent.com/84378451/163487088-dc2005f3-abb6-46b9-901e-085a5dac98d0.png)
![Screenshot 2022-04-15 062149](https://user-images.githubusercontent.com/84378451/163487096-24495786-e79c-45e0-8e40-294cb3f8f006.png)
![Screenshot 2022-04-15 062221](https://user-images.githubusercontent.com/84378451/163487103-d5e540cc-0417-4b62-96a0-5e7fa0fdd7d2.png)

2022-04-15 03:23 UTC, Dreamacro requested changes
All clashx related conditions should not delete

2022-04-15 03:23 UTC, Dreamacro commented on src/containers/Connections/index.tsx
> +            table.createDataColumn(Columns.Process, { minWidth: 100, width: 130, header: t(`columns.${Columns.Process}`) }),
`process` has a value only if there is a relevant rule, it should not put it in front

2022-04-15 03:23 UTC, Dreamacro commented on src/lib/request.ts
> +        process: string
there is no process field

2022-04-15 03:23 UTC, Dreamacro commented on src/lib/request.ts
> +        processPath: string
shoule be `processPath?: string`

2022-04-15 03:23 UTC, Dreamacro commented on src/i18n/zh_CN.ts
> +            logLevel: '信息等级',
should be 日志等级

2022-04-15 03:23 UTC, Dreamacro commented on src/containers/Settings/index.tsx
> +                            onClick={() => setIdentity(false)}>
clashx related condition should not delete

2022-04-15 03:23 UTC, Dreamacro commented on src/containers/Settings/index.tsx
> +            <>{
The fragment here is meaningless

2022-04-15 03:23 UTC, Dreamacro commented on src/containers/Settings/index.tsx
> +        { label: ('debug'), value: 'debug' },
parenthesis is meaningless, and the first letter should be capitalized

2022-04-15 03:23 UTC, Dreamacro commented on src/containers/Logs/index.tsx
> +    const InfoColors = {
It seems that this is not used

2022-04-15 03:23 UTC, Dreamacro commented on src/containers/Logs/index.tsx
> +                                <li className="leading-5 inline-block " style={{ fontSize: '11px' }} key={index}>
should not use style object, use windicss classname instead

2022-04-15 04:40 UTC, MetaCubeX commented on src/containers/Connections/index.tsx
> +            table.createDataColumn(Columns.Process, { minWidth: 100, width: 130, header: t(`columns.${Columns.Process}`) }),
Is `Process` moved to the back display? 
But that doesn't make it easy to look up the rules. 
How about showing `empty` when Process is empty?

2022-04-15 04:46 UTC, Dreamacro commented on src/containers/Connections/index.tsx
> +            table.createDataColumn(Columns.Process, { minWidth: 100, width: 130, header: t(`columns.${Columns.Process}`) }),
maybe you can put it after rule

2022-04-15 13:58 UTC, MetaCubeX commented
没搓完，不小心点提交了，改好再提交哈

2022-04-15 14:11 UTC, Dreamacro commented
就在这个 pr commit 吧，不要再开新的 pr 了

2022-04-15 16:08 UTC, MetaCubeX commented
> 就在这个 pr commit 吧，不要再开新的 pr 了

好的老大，我顺手把适配苹果的启动页搓进去可以吗……

2022-04-20 05:09 UTC, closed without merging